### PR TITLE
Implement `Drop` for `Blink` adapter

### PR DESCRIPTION
**Pull request by dmitry-salin**
`Blink` adapter docs contains:
```
/// [`Blink`] calls [`Drop::drop`] for emplaced values when reset or dropped.
```
But in fact it only does this when reset.

### CODE REVIEW

**Comment by zakarumych** [comment]
Thanks for noticing this!

**Comment by dmitry-salin** [comment]
Thanks for quick response. It seems I needed to apply `fmt` to the entire project. Also `clippy` with `--all-features` flag is failing on stable.

**Comment by zakarumych** [comment]
Yeah, they change set of lints and it's typical for check to fail after some time.
If it's not too much, please, add clippy fixes.

**Comment by dmitry-salin** [comment]
[actions-rs](https://github.com/actions-rs) is no longer maintained. One issue affecting this PR: [clippy-check error](https://github.com/actions-rs/clippy-check/issues/2). I suggest switching to [actions-rust-lang](https://github.com/actions-rust-lang) and [clippy-action](https://github.com/giraffate/clippy-action).

**Comment by zakarumych** [comment]
Looks great!

**Pull request merged**
